# Generated by Django 2.0.3 on 2020-05-18 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'activity',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.SlugField(max_length=200)),
                ('real_name', models.CharField(max_length=50)),
                ('tz', models.CharField(max_length=100)),
                ('activity_periods', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to='users.Activity')),
            ],
            options={
                'db_table': 'user',
            },
        ),
    ]
