# Generated by Django 3.0.6 on 2020-05-19 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200519_0452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='id',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_id',
            field=models.SlugField(max_length=200, primary_key=True, serialize=False),
        ),
    ]
